# Generated by Django 3.2.3 on 2023-02-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20230220_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='creted_by',
            new_name='created_by',
        ),
    ]
